
const buildings = [
    {
      name: "Weed Plant",
      cost: 10,
      bps: 1,
      amount: 0,
      showAt: 0,
      shown: false,
    },
    {
      name: "Underground Garage",
      cost: 50,
      bps: 5,
      amount: 0,
      showAt: 5,
      shown: false,
    },
    {
      name: "Weed Farm",
      cost: 100,
      bps: 10,
      amount: 0,
      showAt: 9,
      shown: false,
    },
    {
      name: "Weed Factory",
      cost: 1000,
      bps: 100,
      amount: 0,
      showAt: 90,
      shown: false,
    },
    {
      name: "Weed Lab",
      cost: 10000,
      bps: 1000,
      amount: 0,
      showAt: 900,
      shown: false,
    },
    {
      name: "Stoner's Den",
      cost: 5000,
      bps: 500,
      amount: 0,
      showAt: 50,
      shown: false,
    },
    {
      name: "Hydroponic Bunker",
      cost: 20000,
      bps: 2000,
      amount: 0,
      showAt: 100,
      shown: false,
    },
    {
      name: "Munchies Factory",
      cost: 50000,
      bps: 5000,
      amount: 0,
      showAt: 200,
      shown: false,
    },
    {
      name: "Cannabis Cathedral",
      cost: 100000,
      bps: 10000,
      amount: 0,
      showAt: 500,
      shown: false,
    },
    {
      name: "Budzooka Dispensary",
      cost: 250000,
      bps: 25000,
      amount: 0,
      showAt: 1000,
      shown: false,
    }
];