
const buildings = [
    {
      name: "Weed Plant",
      cost: 10,
      bps: .5,
      amount: 0,
      showAt: 0,
      shown: false,
    },
    {
      name: "Underground Garage",
      cost: 50,
      bps: 3,
      amount: 0,
      showAt: 25,
      shown: false,
    },
    {
      name: "Weed Farm",
      cost: 100,
      bps: 8,
      amount: 0,
      showAt: 85,
      shown: false,
    },
    {
      name: "Weed Factory",
      cost: 1000,
      bps: 100,
      amount: 0,
      showAt: 950,
      shown: false,
    },
    {
      name: "Weed Lab",
      cost: 5000,
      bps: 250,
      amount: 0,
      showAt: 3500,
      shown: false,
    },
    {
      name: "Stoner's Den",
      cost: 10000,
      bps: 500,
      amount: 0,
      showAt: 6000,
      shown: false,
    },
    {
      name: "Hydroponic Bunker",
      cost: 20000,
      bps: 750,
      amount: 0,
      showAt: 10000,
      shown: false,
    },
    {
      name: "Munchies Factory",
      cost: 50000,
      bps: 1000,
      amount: 0,
      showAt: 25000,
      shown: false,
    },
    {
      name: "Cannabis Cathedral",
      cost: 100000,
      bps: 1500,
      amount: 0,
      showAt: 85000,
      shown: false,
    },
    {
      name: "Budzooka Dispensary",
      cost: 250000,
      bps: 2000,
      amount: 0,
      showAt: 200000,
      shown: false,
    }
];